CREATE DEFINER=`root`@`localhost` PROCEDURE `CONSULTA_LECTOR`(IN LECTOR INT, OUT MAS_DE_15 INT)
BEGIN
	DECLARE EXISTE, CUENTA INT;
DECLARE NOMBRE_LECTOR VARCHAR(45);
/*COMPROBAMOS QUE EL LECTOR EXISTE EN NUETRA BASE DE DATOS*/
SELECT NUMLECTOR INTO EXISTE
FROM LECTORES 
WHERE NUMLECTOR = LECTOR;
/*SI EL LECTOR NO EXISTE EL VALOR DE LA VARIABLE EXISTE SERÁ NULL*/
IF EXISTE IS NULL THEN
	/*SI NO EXISTE SACAREMOS UN MENSAJE DICIÉNDOLO*/
    SELECT CONCAT('EL LECTOR CON NÚMERO ', LECTOR, ' NO EXISTE EN NUESTRA BASE DE DATOS') AS NO_EXISTE;
    SET MAS_DE_15 = 0;
ELSE
	/*SI EXISTE EXTRAEMOS SU NOMBRE Y LA CUENTA DE LOS LIBROS PRESTADOS*/
    /*LOS GUARDAMOS EN LAS VARIABLES NOMBRE_LECTOR Y CUENTA RESPECTIVAMENTE*/
    SELECT NOMLECTOR, COUNT(CODLIBRO) INTO NOMBRE_LECTOR, CUENTA
    FROM LECTORES LE 
    LEFT JOIN PRESTAMOS P ON P.NUMLECTOR = LE.NUMLECTOR
    WHERE LE.NUMLECTOR = LECTOR 
    GROUP BY NOMLECTOR;
    /*SI EL LECTOR NO TENÍA LIBROS PRESTADOS*/
    IF CUENTA = 0 THEN
		SELECT CONCAT('EL LECTOR DE NÚMERO ', LECTOR, ' SE LLAMA ', NOMBRE_LECTOR, '. NO HA COGIDO LIBROS PRESTADOS') AS NO_TIENE_PRESTADOS;
        SET MAS_DE_15 = 0;
    ELSE    
		/*BUSCAMOS AHORA LOS QUE LLEVAN MÁS DE 15 DÍAS PRESTADOS*/
		/*GUARDAMOS LA CUENTA EN EL PARÁMETRO DE SALIDA*/
		SELECT COUNT(CODLIBRO) INTO MAS_DE_15
		FROM PRESTAMOS 
		WHERE NUMLECTOR = LECTOR AND
			  DATEDIFF(CURDATE(), FPRESTA) > 15
		GROUP BY NUMLECTOR;
    /*SACAMOS UN MENSAJE CON TODA LA INFORMACIÓN*/
    SELECT CONCAT('EL LECTOR DE NÚMERO ', LECTOR, ' SE LLAMA ', NOMBRE_LECTOR, '. HA COGIDO ', CUENTA, ' LIBROS PRESTADOS; DE LOS CUALES ', MAS_DE_15, ' LOS TIENE HACE MÁS DE 15 DÍAS') AS RESULTADO;
    END IF;
END IF;
END