CREATE DEFINER=`root`@`localhost` PROCEDURE `LIBROS_POR_TIPO_LECTOR`()

BEGIN
    SELECT CONCAT('Tipo-> ', TIPOLECTOR, ' hay ', COUNT(*), ' lectores') AS RESULTADO
    FROM LECTORES
    WHERE TIPOLECTOR BETWEEN 1 AND 10
    GROUP BY TIPOLECTOR
    ORDER BY TIPOLECTOR ASC;
END
/*
BEGIN
	DECLARE TIPO_LECTOR, CONTADOR INT;
    SET TIPO_LECTOR = 1;
    COMPRUEBA_TIPOS: LOOP
		IF TIPO_LECTOR > 10 THEN
			LEAVE COMPRUEBA_TIPOS;
		ELSE
			IF TIPO_LECTOR IN (SELECT TIPOLECTOR
							   FROM LECTORES) THEN
			   SELECT COUNT(NUMLECTOR) INTO CONTADOR
               FROM LECTORES
               WHERE TIPOLECTOR = TIPO_LECTOR
               GROUP BY TIPOLECTOR;
               
               SELECT CONCAT('Tipo-> ', TIPO_LECTOR, ' hay ', CONTADOR, ' lectores') AS RESULTADO;
	   END IF;
       SET TIPO_LECTOR
   END IF;
END
*/
