CREATE DEFINER=`root`@`localhost` PROCEDURE `MEDIA_DIAS_PRESTADOS`()
BEGIN
	DECLARE MEDIA DOUBLE;

	SELECT ROUND(AVG(DATEDIFF(CURDATE(), FPRESTA)), 2) INTO MEDIA
    FROM DEVOLUCIONES D;
    
    SELECT CONCAT('La media de días de préstamo es ', MEDIA) AS RESULTADO;
END